# docker-compose.yml 
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Use 'development' for dev, switch to 'production' as needed
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env # Make sure this file contains your MongoDB Atlas connection string
    command: npm run dev # Adjust based on your start script
